name: drone_mobile
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  websocket_listener: ^0.0.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.0
  geolocator: ^9.0.0
  udp: ^2.0.3
# add map package (flutter_map or google_maps_flutter)